name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Replace with the desired version

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test

    - name: Pack
      run: dotnet pack -c Release --no-build --include-symbols --include-source

    - name: Publish NuGet package
      uses: nuget/nuget-push@v3
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }} # Add your NuGet API key as a secret in the repository
        nuget-version: ${{ github.ref }}
