name: Build and Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🛠️ Checkout Code
      uses: actions/checkout@v4
      
    - name: ⚙️ Setup .NET SDK
      uses: actions/setup-dotnet@v3

    - name: 📦 AccessSentry - Build & Pack NuGet Package
      run: |
        CSPROJ_PATH="Src/AccessSentry/AccessSentry.csproj"
        VERSION=$(grep '<Version>' "$CSPROJ_PATH" | sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p')
        echo "Package version: $VERSION"
        dotnet restore "$CSPROJ_PATH"
        dotnet pack "$CSPROJ_PATH" \
          --configuration Debug \
          -p:PackageVersion=$VERSION \
          --include-symbols \
          --output ./pkg

    - name: 🚀 Push to GitHub Packages
      run: |
        dotnet nuget push "./pkg/*.nupkg" "./pkg/*.snupkg" \
          --source "nuget.pkg.github.com" \
          --skip-duplicate
